<a href="https://colab.research.google.com/github/nurfnick/3D_Prints_For_Calc_3/blob/main/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#packages used in our project 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sklearn
from sklearn.preprocessing import MinMaxScaler,normalize
from sklearn.decomposition import PCA
import plotly.express as px
import pandas as pd
import tensorflow as tf
from sklearn import preprocessing

In [ ]:
train = pd.read_csv('https://raw.githubusercontent.com/jacmantooth/NASA_deep_learning/main/train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/jacmantooth/NASA_deep_learning/main/test.csv')
print(train.head())
print(test.head())

   label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0      1       0       0       0  ...         0         0         0         0
1      0       0       0       0  ...         0         0         0         0
2      1       0       0       0  ...         0         0         0         0
3      4       0       0       0  ...         0         0         0         0
4      0       0       0       0  ...         0         0         0         0

[5 rows x 785 columns]
   pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0       0       0       0       0  ...         0         0         0         0
1       0       0       0       0  ...         0         0         0         0
2       0       0       0       0  ...         0         0         0         0
3       0       0       0       0  ...         0         0         0         0
4       0       0       0       0  ...         0         0         0         0

[5 rows x 784 columns]


## XOR Example

In [ ]:
A = np.array([[0,0],[0,1],[1,0],[1,1]])
#A = preprocessing.normalize(A)
b = np.array([0,1,1,0])


modelXOR = tf.keras.models.Sequential([
  tf.keras.Input(shape=2),
  tf.keras.layers.Dense(1,activation = 'relu'),
])


modelXOR.compile(optimizer='SGD',
          loss='binary_crossentropy',
          metrics=['accuracy'])
modelXOR.fit(A, b, epochs=5)
print(modelXOR(A))

THRESHOLD:float = 0.5

predictions = modelXOR.predict(A)
np.where(predictions > THRESHOLD, 1,0)

Epoch 1/5
1/1 [==============================] - 1s 720ms/step - loss: 7.7125 - accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 8ms/step - loss: 7.7125 - accuracy: 0.5000
Epoch 3/5
1/1 [==============================] - 0s 3ms/step - loss: 7.7125 - accuracy: 0.5000
Epoch 4/5
1/1 [==============================] - 0s 4ms/step - loss: 7.7125 - accuracy: 0.5000
Epoch 5/5
1/1 [==============================] - 0s 5ms/step - loss: 7.7125 - accuracy: 0.5000
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]], shape=(4, 1), dtype=float32)


array([[0],
       [0],
       [0],
       [0]])

In [ ]:
modelXOR.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
modelXOR(A)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [ ]:
A = np.array([[0,0],[0,1],[1,0],[1,1]])
#A = preprocessing.normalize(A)
b = np.array([0,1,1,0])


modelXOR = tf.keras.models.Sequential([
  tf.keras.Input(shape=2),
  tf.keras.layers.Dense(1,activation=tf.nn.relu),
  # tf.keras.layers.ReLU(max_value=1),
   #tf.keras.layers.Dropout(0.4, noise_shape = None, seed = None),
    #tf.keras.layers.ReLU(threshold=.5),
    tf.keras.layers.Dropout(0.4, noise_shape = None, seed = None)
])


#predictions1 = modelXOR(A).numpy()


loss_fn1 = tf.keras.losses.CategoricalCrossentropy(10)


modelXOR.compile(optimizer='SGD',
              loss='binary_crossentropy',
           metrics=['accuracy'])
modelXOR.fit(A, b, epochs=5)
modelXOR(A)

Epoch 1/5
1/1 [==============================] - 0s 406ms/step - loss: 4.0324 - accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 13ms/step - loss: 4.0222 - accuracy: 0.7500
Epoch 3/5
1/1 [==============================] - 0s 5ms/step - loss: 4.0146 - accuracy: 0.7500
Epoch 4/5
1/1 [==============================] - 0s 7ms/step - loss: 4.0076 - accuracy: 0.7500
Epoch 5/5
1/1 [==============================] - 0s 6ms/step - loss: 4.0012 - accuracy: 0.7500


<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.02168313],
       [0.35694596],
       [0.        ],
       [0.        ]], dtype=float32)>

In [ ]:
from keras.models import Sequential 
from keras.layers import Activation, Dense 
from keras import initializers 
from keras import regularizers 
from keras import constraints

In [ ]:
model = Sequential()

model.add(Dense(8, input_shape=(2,), kernel_initializer = 'he_uniform', 
   kernel_regularizer = None, kernel_constraint = 'MaxNorm', activation = 'relu'))

model.add(Dense(4, activation = 'relu')) 
model.add(Dense(1))

model.compile(optimizer='SGD',
              loss=loss_fn1,
              metrics=['accuracy'])
model.fit(A, b, epochs=5)
model(A)

Epoch 1/5
1/1 [==============================] - 0s 419ms/step - loss: 0.0000e+00 - accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 0.5000
Epoch 3/5
1/1 [==============================] - 0s 6ms/step - loss: 0.0000e+00 - accuracy: 0.5000
Epoch 4/5
1/1 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.5000
Epoch 5/5
1/1 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.5000


<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.03411409],
       [ 0.37917224],
       [-0.15376201],
       [-0.09060283]], dtype=float32)>

In [ ]:
A = np.array([[0,0],[0,1],[1,0],[1,1]])
#A = preprocessing.normalize(A)
b = np.array([0,1,1,0])


modelXOR = tf.keras.models.Sequential([
  tf.keras.Input(shape=2),
  tf.keras.layers.Dense(1,activation='sigmoid'),
])


modelXOR.compile(optimizer='SGD',
          loss='binary_crossentropy',
          metrics=['accuracy'])
modelXOR.fit(A, b, epochs=5)
print(modelXOR(A))

THRESHOLD:float = 0.5

predictions = modelXOR.predict(A)
np.where(predictions > THRESHOLD, 1,0)

Epoch 1/5
1/1 [==============================] - 0s 345ms/step - loss: 0.7088 - accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 6ms/step - loss: 0.7087 - accuracy: 0.2500
Epoch 3/5
1/1 [==============================] - 0s 4ms/step - loss: 0.7086 - accuracy: 0.2500
Epoch 4/5
1/1 [==============================] - 0s 7ms/step - loss: 0.7085 - accuracy: 0.2500
Epoch 5/5
1/1 [==============================] - 0s 3ms/step - loss: 0.7084 - accuracy: 0.2500
tf.Tensor(
[[0.5008232 ]
 [0.38997144]
 [0.47936082]
 [0.36974084]], shape=(4, 1), dtype=float32)


array([[1],
       [0],
       [0],
       [0]])

array([0, 8, 8, 0])

In [12]:
A = np.array([[0,0],[0,1],[1,0],[1,1]])
#A = preprocessing.normalize(A)
b = np.array([0,1,1,0])
mu, sigma = 0, 1
noise = np.random.normal(mu, sigma, [4,2])
Anoise = np.append(A,A + noise, axis = 0)
b = np.append(b,b)
print(Anoise)
modelXOR = tf.keras.models.Sequential([
  #tf.keras.layers.GaussianNoise(.01, input_shape=(2,)),
  tf.keras.layers.Dense(2,activation='relu'),
  tf.keras.layers.Dense(1,activation='sigmoid'),
])

modelXOR.compile(optimizer='SGD',
          loss='binary_crossentropy',
          metrics=['accuracy'])
modelXOR.fit(Anoise, b, epochs=25)
print(modelXOR(Anoise))

THRESHOLD:float = 0.5
predictions = modelXOR.predict(Anoise)
print(np.where(predictions >= THRESHOLD, 1,0))
print(modelXOR(A))
predictions = modelXOR.predict(A)
np.where(predictions >= THRESHOLD, 1,0)

[[ 0.          0.        ]
 [ 0.          1.        ]
 [ 1.          0.        ]
 [ 1.          1.        ]
 [ 0.09022374 -0.62196487]
 [-2.04352316  1.51676673]
 [ 0.67913771  1.55554525]
 [ 2.61859584  1.29857002]]
Epoch 1/25
1/1 [==============================] - 0s 365ms/step - loss: 0.8869 - accuracy: 0.5000
Epoch 2/25
1/1 [==============================] - 0s 4ms/step - loss: 0.8835 - accuracy: 0.3750
Epoch 3/25
1/1 [==============================] - 0s 6ms/step - loss: 0.8801 - accuracy: 0.3750
Epoch 4/25
1/1 [==============================] - 0s 6ms/step - loss: 0.8768 - accuracy: 0.3750
Epoch 5/25
1/1 [==============================] - 0s 4ms/step - loss: 0.8735 - accuracy: 0.3750
Epoch 6/25
1/1 [==============================] - 0s 4ms/step - loss: 0.8703 - accuracy: 0.3750
Epoch 7/25
1/1 [==============================] - 0s 4ms/step - loss: 0.8671 - accuracy: 0.3750
Epoch 8/25
1/1 [==============================] - 0s 8ms/step - loss: 0.8639 - accuracy: 0.3750
Epoch 9/25
1/

array([[1],
       [0],
       [0],
       [0]])

In [20]:
 def treetest(first, second):
   if first == second: 
    print(0),
   if first != second: 
    print(1)
treetest(1,0)



def tree (a):
  new_m=[]
  for j in range(len(a)):
    if a[j][0]== a[j][1] :
        new_m.append(0)
    else:
        new_m.append(1)
  return (new_m)
tree(A)


1


[0, 1, 1, 0]

In [16]:
from sklearn.tree import DecisionTreeClassifier
b = np.array([0,1,1,0])
clf = DecisionTreeClassifier()

clf.fit(A,b)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [19]:
clf.predict(Anoise)

array([0, 1, 1, 0, 0, 1, 0, 0])

In [21]:
tree(Anoise)

[0, 1, 1, 0, 1, 1, 1, 1]